# Provide the name and location of the integrated functional elements (IFEs) file.
ifes_file: "resources/ifes_3.386_3.0A_full_Aug_22.csv"

# What are the paths of the directories that will hold structures?
original_mmcif_dir: "resources/original_mmCIF_files/"
h_omitted_mmcif_dir: "results/h_omitted_mmcif_dir/"
disordered_mmcif_dir: "results/disordered_mmcif_files/"
modified_mmcif_dir: "results/modified_mmcif_files/"
chain_pdb_dir: "results/chain_pdb_files/"
clipped_structures_dir: "results/clipped_structures/"

# What are the search radii?
search_dist: 4.1
count_dist_1: 7.5
count_dist_2: 12.5

# What are the cutoffs?
h_dist_max: 2.5
h_ang_min: 140.0

# Should a custom ordering be applied for location_1_residues.csv and location_2_residues.csv?
custom_order: true

# Should PDB ID 9E71 be expressed in scientific notation (i.e., "9e+71") for location_2_residues.csv?
9E71_sci_not: true

# What are the residue and atom names of the donors that are to be considered?
dual_h_donors:
  - 'A.N6'
  - 'C.N4'
  - 'G.N2'

# For the clustering, what validation score will be used (sil, ch, or db)?
val_score: "sil"

# For the clustering, should leaf labels be included with the dendrograms?
leaf_labels: false

# Should the folder with the mmCIF files fetched from the PDB be removed to save space?
remove_original_mmcif: false

# Should the folder with the disordered mmCIF files be removed to save space?
remove_disordered_mmcif: false

# Should the mmCIF of the modified structures be saved?
save_modified_mmcif: true

# Should the commit hash be written to output data files?
commit_hash: false

# Should the original version of id_rep_struct be used?
original_clustering: true
